language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_install:
  - composer self-update

before_script:
  - cp .env.example .env
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - php artisan key:generate
  - php artisan make:migrate


script: ./vendor/bin/phpunit